NUMPY

Para importar numpy, utilize: import numpy as np

Você também pode utilizar: from numpy import * .Isso evitará a utilização de np., mas este comando importará todos os módulos do NumPy

Resumidamente o numpy serve para manipulação de objetos do tipo array

In [1]:
import numpy as np

Criando array com numpy. Como já vimos utilizando muito a manipulação de dados utilizando listas e dicionário. Porém, numpy permite a criação de arrays.

Criando array a partir de uma lista

In [5]:
list = [1,2,3,4,5]
array1 = np.array(list)

print(array1)

[1 2 3 4 5]


O que diferencia um array de uma lista, é que um array ele aceita apenas um tipo de dados enquanto uma lista diversos tipos. Vejamos:

In [6]:
lista = [1,2,3,4,'a','b','c']
print(lista)

[1, 2, 3, 4, 'a', 'b', 'c']


In [8]:
array = np.array(lista)
print(array) #transformou todos os elementos para string inclusive os numéricos

['1' '2' '3' '4' 'a' 'b' 'c']


Imprimindo um elemento específico de um array

In [9]:
array[0]

'1'

In [10]:
for pos in range(0, len(array)):
    print(array[pos])

1
2
3
4
a
b
c


In [11]:
for elementos in array:
    print(elementos)

1
2
3
4
a
b
c


Alterando um elemento de um array

In [12]:
array[1]

'2'

In [13]:
array[1] = 'dois'

In [14]:
array

array(['1', 'dois', '3', '4', 'a', 'b', 'c'], dtype='<U11')

In [19]:
#formas de obter o tamanho de um array

#usando len
print(len(array))

#usando shape
array.shape

7


(7,)

Criando um array usando uma função arange

In [27]:
array2 = np.arange(0, 52, 5)

array3 = np.arange(0, 10, 0.5)

In [28]:
array2

array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Verificar o tipo de dados presentes no array

In [26]:
print('Array:', array)
print('tipo:', array.dtype)
print('\nArray:', array2)
print('tipo:', array2.dtype)

Array: ['1' 'dois' '3' '4' 'a' 'b' 'c']
tipo: <U11

Array: [ 0  5 10 15 20 25 30 35 40 45 50]
tipo: int32


criando um array com elementos na diagonal

In [33]:
array3 = [1,2,3,4]
np.diag(array3)
#coloquei os elementos de um array na diagonal de outro array

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
#criando array de valores bolleanos
lista = [True, False, True, False]
array4 = np.array(lista)
type(array4)

numpy.ndarray

In [38]:
#criando array de strings
lista = ['Arlon','Jessica','Regina','Maria']
array5 = np.array(lista)
type(array5)

numpy.ndarray

Criando uma matriz

In [41]:
matriz = np.array([[1,2,3,4],[5,6,7,8]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Obtendo o tamanho da matriz, em termos de linhas e colunas

In [43]:
matriz.shape
#(linhas, colunas)

(2, 4)

Criando uma matriz a partir de lista de listas

In [49]:
lista = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matriz2 = np.array(lista)
print(matriz2)
matriz2.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

Uma observação importante, para que ocorra a construção da matriz, as listas devem possuir a mesma quantidade de colunas

In [50]:
#verificando o tipo de dados
type(matriz2)

numpy.ndarray

In [51]:
#Para verificar o tamanho de uma matriz usa-se
matriz2.size

12

In [52]:
#Porém, para verfiicar o tamanho das linhas e colunas
matriz2.shape

(3, 4)

In [53]:
#Verificando o tipo dos dados que estão dentro da matriz
matriz2.dtype

dtype('int32')

In [54]:
#Acessando um item específico de uma matriz

In [58]:
print(matriz2)
print(matriz2[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7


In [61]:
#alterando um item específico de uma matriz
matriz2[1,2] = -7
print(matriz2)

[[ 1  2  3  4]
 [ 5  6 -7  8]
 [ 9 10 11 12]]


In [66]:
#Criando uma matriz com numeros inteiros porém definindo o tipo dos dados como float
matrizfloat = np.array([[1,2,3],[4,5,6]], dtype=float)

matrizfloat

array([[1., 2., 3.],
       [4., 5., 6.]])

In [69]:
matrizfloat.shape
matrizfloat[1, 2] = matrizfloat[1, 2] * -1
matrizfloat

array([[ 1.,  2.,  3.],
       [ 4.,  5., -6.]])